DomandaOnLine/DomandeOnline/Models/Domanda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DomandeOnline.Models
{
	public class Domanda
	{
		public int IdDomanda { get; set; }
		public string Bando { get; set; }
		public DateTime DataPresentazione { get; set; }
	}
}

DomandaOnLine/DomandeOnline/Models/Progetto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DomandeOnline.Data
{
	public partial class Progetto
	{
		public static class Tipo
		{
			public const string ITALIA = "ITALIA";
			public const string ESTERO = "ESTERO";
		}

		public List<Regione> RegioniAmmesse;
		public List<Provincia> ProvinceAmmesse;
		public bool Asse1NEET { get { return ProvinceAmmesse != null; } }
		public bool Asse1bisDisoccupati { get { return RegioniAmmesse != null; } }
	}

	public class ProgettoDto
	{
		public string CodiceProgetto { get; set; }
		public string TipoProgetto { get; set; }
		public int CodiceSede { get; set; }
		public string IndirizzoSede { get; set; }
		public string Area { get; set; }
		public string TitoloProgetto { get; set; }
		public string CodiceEnte { get; set; }
		public string NomeEnte { get; set; }
		public string Regione { get; set; }
		public string Provincia { get; set; }
		public string Comune { get; set; }
		public string Settore { get; set; }
		public string Misure { get; set; }
		public int NumeroGiovaniMinoriOpportunità { get; set; }
		public string EsteroUE { get; set; }
		public string Tutoraggio { get; set; }
		public bool Preferito { get; set; }
		public int NumeroDomande { get; set; }
		public int? IdTipoGG { get; set; }
		public string EnteAttuatore { get; set; }

	}
}

DomandaOnLine/DomandeOnline/Controllers/DomandaPartecipazioneController.cs
using DomandeOnline.Code;
using DomandeOnline.Data;
using DomandeOnline.Exceptions;
using DomandeOnline.Models;
using DomandeOnline.Models.Extensions;
using iTextSharp.text.pdf.parser;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PdfSharp;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TheArtOfDev.HtmlRenderer.PdfSharp;

namespace DomandeOnline.Controllers
{

	[Authorize(Roles = Role.UTENTE_CREDENZIALI + "," + Role.UTENTE_SPID)]
	public class DomandaPartecipazioneController : SmartController
	{
		protected string RenderPartialViewToString(string viewName, object model)
		{
			if (string.IsNullOrEmpty(viewName))
				viewName = ControllerContext.RouteData.GetRequiredString("action");

			if (model != null)
				ViewData.Model = model;

			using (StringWriter sw = new StringWriter())
			{
				ViewEngineResult viewResult = ViewEngines.Engines.FindView(ControllerContext, viewName, "_layoutStampa");
				ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
				viewResult.View.Render(viewContext, sw);

				return sw.GetStringBuilder().ToString();
			}
		}

		/// <summary>
		/// Restituisce l'id del gruppo del bando scelto
		/// </summary>
		/// <returns>null se non presente nella sessione</returns>
		private int? GetIdGruppo()
		{

			if (System.Web.HttpContext.Current.Session["GruppoSelezionato"] == null)
			{
				using (var context = new Entities())
				{
					var bandi = context.Bando
					.Where(x => DbFunctions.AddDays(x.DataScadenza, x.GiorniPostScadenza ?? 30) >= DateTime.Now);
					if (bandi.Count() == 1)
					{
						return bandi.First().Gruppo;
					}else{
						return null;
					}
				}


			}
			if (!(System.Web.HttpContext.Current.Session["GruppoSelezionato"] is string))
			{
				return null;
			}
			if (!int.TryParse(System.Web.HttpContext.Current.Session["GruppoSelezionato"] as string, out int idGruppo))
			{
				return null;
			}
			return idGruppo;
		}

		private DomandaPartecipazione GetDomanda(Entities context)
		{
			/* Recupero codice fiscale utente */
			//ApplicationUser utente;
			//try
			//{
			//	utente = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>()
			//		.FindById(User.Identity.GetUserId());
			//}
			//catch (Exception e)
			//{
			//	throw new Exception("Errore nella lettura dell'utente dal DB", e);
			//}
			string codiceFiscale = User.Identity.GetCodiceFiscale();
			//if (string.IsNullOrEmpty(utente.CodiceFiscale))
			if (string.IsNullOrEmpty(codiceFiscale))
			{
				throw new AccountException("Utente senza codice fiscale");
			}

			DomandaPartecipazione domanda;
			int? idGruppo = GetIdGruppo();
			if (!context.Bando.Where(x => x.Gruppo == idGruppo && x.DataScadenza > DateTime.Now).Any())
			{
				Log.Information(LogEvent.DOMANDA_ONLINE, $"Operazione effettuata dall'utente a bando scaduto {idGruppo}");
				return null;
			}
			try
			{
				domanda = context.DomandaPartecipazione
				.Where(x => x.CodiceFiscale == /*utente.CodiceFiscale*/ codiceFiscale &&
							x.GruppoBando == idGruppo &&
							x.DataAnnullamento == null)
				.Include(x => x.Progetto)
				.Include(x => x.Progetto.MinoreOpportunita)
				.Include(x => x.Progetto.Programma)
				.Include(x => x.Motivazione)
				.Include(x => x.MotivoAnnullamento)
				.SingleOrDefault();
				if (domanda.Progetto?.Programma?.GaranziaGiovane != null)
				{
					GaranziaGiovani garanziaGiovane = domanda.Progetto?.Programma?.GaranziaGiovane;
					List<Regione> regioniAmmesse = context.RequisitiGaranziaGiovani
						.Where(r => r.TipoGG == garanziaGiovane.Descrizione && r.IdRegione != null)
						.Include(r => r.Regione.Provincia)
						.Select(r => r.Regione)
						.ToList();
					if (regioniAmmesse.Count > 0)
					{
						domanda.Progetto.RegioniAmmesse = regioniAmmesse;
					}
					List<Provincia> provinceAmmesse = context.RequisitiGaranziaGiovani
						.Where(r => r.TipoGG == garanziaGiovane.Descrizione && r.IdProvincia != null)
						.Select(r => r.Provincia)
						.ToList();
					if (provinceAmmesse.Count > 0)
					{
						domanda.Progetto.ProvinceAmmesse = provinceAmmesse;
					}
				}
			}
			catch (Exception e)
			{

				throw new Exception("Errore nella lettura della domanda dal DB", e);
			}

			return domanda;
		}


		/**** Actions ****/
		public ActionResult SelezionaBando()
		{

			try
			{
				using (var context = new Entities())
				{

					var bandi = context.Bando
						.Where(x => DbFunctions.AddDays(x.DataScadenza, x.GiorniPostScadenza ?? 30) >= DateTime.Now);
					if (bandi.Count() == 1)
					{
						return RedirectToAction("Index", new { gruppo = bandi.First().Gruppo });
					}
					return View(bandi.ToList());
				}
			}
			catch (Exception e)
			{
				Log.Error(LogEvent.DOMANDA_ONLINE, "Errore nella lettura del bando dal DB",e);
				return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest, "Errore interno");
			}
		}
        public ActionResult Index(int? gruppo)
		{
			{
				/* Recupero gruppo del bando selezionato (Tramite variabile di sessione) */
				int idGruppo;
				if (gruppo.HasValue)
				{
					/* Viene impostata la variabile di sessione con il gruppo selezionato */
					System.Web.HttpContext.Current.Session["GruppoSelezionato"] = gruppo.ToString();
					idGruppo = gruppo.Value;
				}
				else
				{
					int? idGruppoScelto = GetIdGruppo();
					if (!idGruppoScelto.HasValue)
					{
						return RedirectToAction("SelezionaBando");
					}
					System.Web.HttpContext.Current.Session["GruppoSelezionato"] = idGruppoScelto.ToString();
					idGruppo = idGruppoScelto.Value;
				}

				///* Controllo Se il bando è scaduto */
				//using (var context = new Entities())
				//{
				//	if (!context.Bando.Where(x => x.Gruppo == idGruppo && x.DataScadenza > DateTime.Now).Any())
				//	{
				//		return RedirectToAction("SelezionaBando");
				//	}
				//}
				/* Recupero codice fiscale utente */
				//ApplicationUser utente;
				//try
				//{
				//	utente = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>()
				//		.FindById(User.Identity.GetUserId());
				//}
				//catch (Exception e)
				//{
				//	Log.Error(LogEvent.DOMANDA_ONLINE, "Errore nel recupero del codice fiscale dell'utente",e);
				//	throw e;
				//}
				//if (utente == null)
				//{
				//	return RedirectToAction("LogOff", "Account");
				//}
				//if (string.IsNullOrEmpty(utente.CodiceFiscale))
				if (string.IsNullOrEmpty(User.Identity.GetCodiceFiscale()))
				{
					Log.Error(LogEvent.DOMANDA_ONLINE, "Un utente senza codice fiscale ha acceduto alla pagina della domanda");
					return RedirectToAction("LogOff", "Account");
				}
				/* Controllo età */
				//var eta = GetEta(utente.DataNascita.Value);
				var eta = GetEta(User.Identity.GetDataNascita());
				if (!eta.HasValue)
				{
					Log.Error(LogEvent.DOMANDA_ONLINE, "Un utente senza data di nascita ha acceduto alla pagina della domanda");
					return HttpNotFound("Errore interno");
				}


                //var properties = new { utente.CodiceFiscale, idGruppo };
                var properties = new { CodiceFiscale = User.Identity.GetCodiceFiscale(), IdBando = idGruppo };

				/* Recupero domanda */
				try
				{
					using (var context = new Entities())
					{
						//Codice fiscale utente
						string codiceFiscale = User.Identity.GetCodiceFiscale();
						//ID utente
						string UserID = User.Identity.GetUserId();

						Bando bando = context.Bando.Where(x => x.Gruppo == idGruppo).FirstOrDefault();
						if (bando==null)
						{
							return RedirectToAction("SelezionaBando");
						}

						var domanda = context.DomandaPartecipazione
							.Where(x => x.CodiceFiscale == /*utente.CodiceFiscale*/ codiceFiscale &&
										x.GruppoBando == idGruppo &&
										x.DataAnnullamento == null)
							.Include(x => x.Progetto)
							.Include(x => x.Progetto.MinoreOpportunita)
							.Include(x => x.Progetto.Programma)
							.Include(x => x.Motivazione)
							.Include(x => x.MotivoAnnullamento)
							.SingleOrDefault();
						if (domanda?.Progetto?.Programma?.GaranziaGiovane != null)
						{
							GaranziaGiovani garanziaGiovane = domanda.Progetto?.Programma?.GaranziaGiovane;
							List<Regione> regioniAmmesse = context.RequisitiGaranziaGiovani
								.Where(r => r.TipoGG == garanziaGiovane.Descrizione && r.IdRegione != null)
								.Include(r => r.Regione.Provincia)
								.Select(r => r.Regione)
								.ToList();
							if (regioniAmmesse.Count > 0)
							{
								domanda.Progetto.RegioniAmmesse = regioniAmmesse;
							}
							List<Provincia> provinceAmmesse = context.RequisitiGaranziaGiovani
								.Where(r => r.TipoGG == garanziaGiovane.Descrizione && r.IdProvincia != null)
								.Select(r => r.Provincia)
								.ToList();
							if (provinceAmmesse.Count > 0)
							{
								domanda.Progetto.ProvinceAmmesse = provinceAmmesse;
							}
						}

						/*Se il bando è chiuso ed è stata presentata la domanda e non sono passati i giorni stabiliti viene visualizzata la domanda presentata*/
						if (DateTime.Now.AddDays(-bando.GiorniPostScadenza ?? 30) <= bando.DataScadenza && domanda?.DataPresentazione != null)
						{
							if (DateTime.Now>bando.DataFineAnnullamento)
							{
								ViewData["Scaduto"] = true;
							}
							return View("Domanda", domanda);
						}
						if (DateTime.Now > bando.DataScadenza)
						{
							return View("Domanda", null);
						}

						int etaMassima = 28;
						/* Verifica Volontari COVID */
						if (context.VolontarioInterruzioneCovid
								.Where(x => x.CodiceFiscale == /*utente.CodiceFiscale*/ codiceFiscale && x.AnnoInterruzione==2020)
								.Any())
						{

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/Allegati.cshtml
@{
    ViewBag.Title = "Inserimento Allegati";
}

<div class="row">
	<div class="inlineHeader">
		<a href="@Url.Action("Index")" class="btn btn-info">Torna alla Domanda</a>
		<h2>Inserimento Allegati</h2>
	</div>
</div>
<hr />
<form action="@Url.Action("InserisciAllegato")" method="post">
	<h3>Curriculum Vitae</h3>
	<div class="row">
		<div class="form-group col-md-6">
			<label for="fileCV">Allegato CV</label>
			<input name="allegatoCV" type="file" class="form-control required" id="fileCV">
			<small class="form-text text-danger" style="display:none"></small>
		</div>

	</div>

</form>

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/Annullamento.cshtml
@using DomandeOnline.Data
@model DomandaPartecipazione
@{
	ViewBag.Title = "Domanda";
	string errore = TempData["Errore"] as string;
}

@section scripts{
	<script type="text/javascript">
		function Controlli() {
			elem = $('#cbMotivo');
			if (elem.val() == "") {
				$(elem).css("border-color", "red");
				$(elem).parent().find("small").html("Campo obbligatorio").show();
				return false;
			} else {
				$(elem).parent().removeClass("errorBorder");
				$(elem).parent().find("small").hide();
				return true;
			}
		}

	</script>
}

@if (!string.IsNullOrEmpty(errore))
{
	<div class="alert alert-danger alert-dismissible fade in">
		@Html.Raw(errore)
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}

<h2>Si sta per richiedere l'annullamento della domanda</h2>
<p>Codice Domanda: @Model.Id</p>
<p>Data Presentazione: @Model.DataPresentazione</p>

<p>Per presentare una nuova domanda occorre attendere il tempo di elaborazione della richiesta di annullamento (circa 24 ore).</p>
<form action="@Url.Action("ConfermaAnnullamento")" method="post" onsubmit="return Controlli();">
	<div class="row">
		<div class="form-group col-md-4">
			<label for="cbMotivo">Motivo</label>
			<select name="idMotivo" id="cbMotivo" class="form-control" onchange="Controlli();">
				<option></option>
				@foreach (MotivoAnnullamento ambito in (IEnumerable<MotivoAnnullamento>)ViewData["Motivi"])
				{
					<option value="@ambito.Id">@ambito.Descrizione</option>
				}
			</select>
			<small class="form-text text-danger" style="display:none"></small>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-md-4">
			<button class="btn btn-info" type="submit" >Annulla Domanda</button>
		</div>
	</div>
</form>

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/Conferma.cshtml
@model DomandeOnline.Data.DomandaPartecipazione
@{
	ViewBag.Title = "Conferma";
}
<div class="row">
	<div class="inlineHeader">
		<a href="@Url.Action("Index")" class="btn btn-info">Torna alla Domanda</a>
		<h2>Conferma invio domanda</h2>
	</div>
</div>
<hr />
<p>Attenzione: non hai compilato i campi relativi alle informazioni sugli ulteriori titoli posseduti e sulle esperienze maturate e non hai allegato il curriculum vitae. Pertanto in sede di valutazione della domanda ti verrà attribuito punteggio solo per il titolo di studio dichiarato nella sezione “Dati e Dichiarazioni”.</p>
<form action="@Url.Action("Riepilogo",new { conferma=true})" method="post">
	<button class="btn btn-info bottom" type="submit">Conferma</button>
</form>

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/Domanda.cshtml
@using DomandeOnline.Data
@model DomandaPartecipazione
@{
	ViewBag.Title = "Domanda";
	string errore = (ViewData["Errore"] as string)?? (TempData["Errore"] as string);

}
@if (!string.IsNullOrEmpty(errore))
{
	<div class="alert alert-danger alert-dismissible fade in">
		@Html.Raw(errore)
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}
@if (Model?.DataPresentazione == null)
{
	<a class="btn btn-primary" href="@Url.Action("SelezionaBando")">< Seleziona Bando</a>
	<h2>Il bando è chiuso. Non è possibile presentare una domanda.</h2>
}
else
{
	<a class="btn btn-primary" href="@Url.Action("SelezionaBando")">< Seleziona Bando</a>
	string urlSito = Model.Progetto.Sito;
	if (!urlSito.Contains("://"))
	{
		urlSito = "http://" + urlSito;
	}


	if (Model.DataRichiestaAnnullamento == null)
	{
		<h2>Hai presentato la domanda</h2>
		<p>Codice Domanda: @Model.Id</p>
		<p>Data Presentazione: @Model.DataPresentazione</p>
		<p>Per conoscere la data delle selezioni consulta il sito <a href="@urlSito" target="_blank" title="Vai al sito (Si apre in un'altra finestra)">@Model.Progetto.Sito</a></p>

		<p>Puoi scaricare la ricevuta della domanda premendo il seguente pulsante.</p>
		<form action="@Url.Action("Download",new {idDomanda=Model.Id})" method="post">
			<button class="btn btn-info" type="submit">Stampa Domanda</button>
		</form>
		if(ViewData["Scaduto"] == null)
		{
			<hr />
			<p>Puoi annullare domanda premendo il seguente pulsante.</p>
			<form action="@Url.Action("Annullamento",new {idDomanda=Model.Id})" method="post">
				<button class="btn btn-info" type="submit">Annulla Domanda</button>
			</form>
		}

	}
	else
	{
		<h2>Hai effettuato richiesta di annullamento della domanda</h2>
		<p>Codice Domanda: @Model.Id</p>
		<p>Data Presentazione: @Model.DataPresentazione</p>
		<p>Data Richiesta Annullamento: @Model.DataRichiestaAnnullamento</p>
		<p>Motivo Annullamento: @(Model.MotivoAnnullamento?.Descrizione)</p>
	}
}

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/DomandePresentate.cshtml
@using DomandeOnline.Models
@model IEnumerable<Domanda>
@{
	ViewBag.Title = "Domande Presentate";
	string errore = TempData["Errore"] as string;
}
@if (!string.IsNullOrEmpty(errore))
{
	<div class="alert alert-danger alert-dismissible fade in">
		@Html.Raw(errore)
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}
<div class="row">
	<div class="inlineHeader">
		<a class="btn btn-info" href="@Url.Action("SelezionaBando", "DomandaPartecipazione")">Torna al bando</a>
		<h2>Domande presentate</h2>
	</div>
</div>

@if (Model == null || Model.Count() == 0)
{
	<h3>Non hai presentato nessuna domanda.</h3>
}
else
{
	<hr />
	<form action="@Url.Action("Download")" method="post" target="_blank">
		<table class="table table-striped">
			<thead>
				<tr>
					<th></th>
					<th>Bando</th>
					<th>DataPresentazione</th>
				</tr>
			</thead>
			<tbody>
				@foreach (Domanda domanda in Model)
				{
					<tr>
						<td>
							<div class="buttonColumn" style="font-size:2em">
								@*Pulsante Seleziona bando*@
								<button class="btn-link" name="idDomanda" value="@domanda.IdDomanda" type="submit" title="Scarica Domanda">
									<span class="glyphicon glyphicon-download"></span>
								</button>
							</div>
						</td>
						<td>
							@domanda.Bando
						</td>
						<td>
							@domanda.DataPresentazione
						</td>
					</tr>
				}
			</tbody>
		</table>
	</form>

}

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/Errore.cshtml
@using DomandeOnline.Data
@model DomandaPartecipazione
@{
	ViewBag.Title = "Errore";
}

<h2>@ViewData["Errore"]</h2>
<p>Non puoi procedere alla presentazione della domanda di partecipazione al Servizio Civile		poiché non sono soddisfatti i requisiti.</p>

DomandaOnLine/DomandeOnline/Views/DomandaPartecipazione/SelezionaBando.cshtml
@using DomandeOnline.Data
@model IEnumerable<Bando>
@{
	ViewBag.Title = "Seleziona Bando";
}
@if (Model == null || Model.Count() == 0)
{
	<h3>Attualmente non è presente nessun bando attivo per la partecipazione al Servizio civile.</h3>
}
else
{
	<h2>Seleziona Bando</h2>
	<hr />
	<h3>Seleziona un bando al quale presentare la domanda di partecipazione</h3>
	<hr />
	<form action="@Url.Action("Index")" method="post">
		<table class="table table-striped">
			<thead>
				<tr>
					<th></th>
					<th>Bando</th>
					<th>Scadenza</th>
				</tr>
			</thead>
			<tbody>
				@foreach (Bando bando in Model)
				{
					<tr>
						<td>
							<div class="buttonColumn">
								@*Pulsante Seleziona bando*@
								<button class="btn-link" name="gruppo" value="@bando.Gruppo" type="submit" title="SelezionaBando">
									<span class="glyphicon glyphicon-ok"></span>
								</button>
							</div>
						</td>
						<td>
							@bando.Descrizione
						</td>
						<td>
							@bando.Scadenza
						</td>
					</tr>
				}
			</tbody>
		</table>
	</form>
}
@*<br />
<a class="btn btn-info" href="@Url.Action("DomandePresentate", "DomandaPartecipazione")">Visualizza domande presentate</a>*@