SistemaUnico/Registrazione/Models/Accesso.cs
using RegistrazioneSistemaUnico.Helpers.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RegistrazioneSistemaUnico.Models
{
	public class Accesso
	{
		[DisplayName("Codice Fiscale")]
		[Required(ErrorMessage = "Campo obbligatorio")]
		[CodiceFiscale]
		public string CodiceFiscale { get; set; }

		[DisplayName("Nome")]
		[Required(ErrorMessage = "Campo obbligatorio")]
		public string Nome { get; set; }

		[DisplayName("Cognome")]
		[Required(ErrorMessage = "Campo obbligatorio")]
		public string Cognome { get; set; }

		[DisplayName("Data di nascita")]
		[Required(ErrorMessage = "Campo obbligatorio")]
		[Date]
		public DateTime? DataNascita { get; set; }
	}
}

SistemaUnico/Registrazione/Controllers/AccessoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RegistrazioneSistemaUnico.Data;
using RegistrazioneSistemaUnico.Helpers;
using RegistrazioneSistemaUnico.Models;
using RegistrazioneSistemaUnico.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using SpidService;
using static RegistrazioneSistemaUnico.Services.TokenService;

namespace RegistrazioneSistemaUnico.Controllers
{
	public class AccessoController : SmartController
	{


		public AccessoController(RegistrazioneContext registrazioneContext) : base(registrazioneContext)
		{
		}


		public IActionResult Spid(Accesso parameters)
		{
			if (Parametri.SimulazioneSPID!="true")
			{
				return NotFound();
			}
			return View(parameters);
		}


		[HttpGet]
		public IActionResult LoginSpid(string token)
		{
			ServiceClient service = new ServiceClient(ServiceClient.EndpointConfiguration.BasicHttpBinding_IService, Parametri.SpidServiceEndpoint);
			userInfo result;
			try
			{
				result = service.getUserInfo(token);
			}
			catch (Exception ex)
			{
				Log.Error(LogEvent.ERRORE_ACCESSO_SPID, "Errore Access al Servizio SPID",ex);
				TempData["Error"] = "Errore nell'accesso con SPID. Consultare il supporto tecnico";
				return RedirectToAction("Index", "Home");
			}
			if (result.Spidcode==null || result.Spidcode.First() == '-')
			{
				Log.Error(LogEvent.ERRORE_ACCESSO_SPID, result.Spidcode);
				TempData["Error"] = $"Errore nell'accesso con SPID {result.Spidcode}";
				return RedirectToAction("Index", "Home");
			}
			int i = result.FiscalNumber.IndexOf("-");
			if (i >= 0)
			{
				result.FiscalNumber=(result.FiscalNumber.Substring(i + 1, result.FiscalNumber.Length - i - 1));
			}
			string jwtToken = GenerateSimpleToken(result);
			Response.Cookies.Append("jwtToken", jwtToken);
			Log.SetUsername(result.FiscalNumber, $"{result.Name} {result.Surname}".Trim());


			Log.Information(LogEvent.ACCESSO_EFFETTUATO);
			// Redirect in base ai dati della sessione
			Registrazione registrazione = GetRegistrazione();
			if (registrazione == null)
			{
				return RedirectToAction("Index");
			}
			//Variato Utente
			if (registrazione.CodiceFiscaleRappresentanteLegale != result.FiscalNumber)
			{
				HttpContext.Session.Remove("Registrazione");
				return RedirectToAction("Index");
			}
			if (!string.IsNullOrEmpty(registrazione.CodiceFiscaleEnte))
			{
				Log.SetEnte(registrazione.CodiceFiscaleEnte);
			}
			if (registrazione.Nome == null)
			{
				return RedirectToAction("Index", "Registrazione");
			}
			return RedirectToAction("Riepilogo", "Registrazione");
		}

		[HttpPost]
		public IActionResult LoginSpid(Accesso parameters)
		{
			if (Parametri.SimulazioneSPID != "true")
			{
				return NotFound();
			}
			if (ModelState.IsValid)
			{
				ServiceClient service = new ServiceClient(ServiceClient.EndpointConfiguration.BasicHttpBinding_IService, Parametri.SpidServiceEndpoint);

				userInfo result2 = service.getUserInfo(parameters.CodiceFiscale);
				userInfo result = new userInfo()
				{
					Name = parameters.Nome,
					Surname = parameters.Cognome,
					DateOfBirth = parameters.DataNascita.Value.ToString("yyyy-MM-dd"),
					FiscalNumber = parameters.CodiceFiscale.ToUpper()
				};

				string jwtToken = TokenService.GenerateSimpleToken(result);
				Response.Cookies.Append("jwtToken", jwtToken);
				Log.SetUsername(result.FiscalNumber, $"{result.Name} {result.Surname}".Trim());


				Log.Information(LogEvent.ACCESSO_EFFETTUATO);
				// Redirect in base ai dati della sessione
				Registrazione registrazione = GetRegistrazione();
				if (registrazione == null )
				{
					return RedirectToAction("Index");
				}
				//Variato Utente
				if (registrazione.CodiceFiscaleRappresentanteLegale != result.FiscalNumber)
				{
					HttpContext.Session.Remove("Registrazione");
					return RedirectToAction("Index");
				}
				if (!string.IsNullOrEmpty(registrazione.CodiceFiscaleEnte))
				{
					Log.SetEnte(registrazione.CodiceFiscaleEnte);
				}
				if (registrazione.Nome == null)
				{
					return RedirectToAction("Index", "Registrazione");
				}
				return RedirectToAction("Riepilogo", "Registrazione");
			}

			return View("Spid", parameters);

		}


		[Authorize]
		public IActionResult Index()
		{
			List<UtenteEnte> enti = context.UtenteEnte
				.Where(x => x.CodiceFiscale == utente.FiscalNumber)
				.ToList();
			return View(enti);
		}



		[Authorize]
		[HttpPost]
		public IActionResult Accedi(string Username, string Albo)
		{
			UtenteEnte ente = context.UtenteEnte
				.Where(
					x => x.CodiceFiscale == utente.FiscalNumber && 
					x.Username == Username && 
					x.Albo==Albo)
				.FirstOrDefault();
			if (ente == null)
			{
				ViewData["Error"] = "Utente non abilitato all'accesso";
				return RedirectToAction("Index");
			}
			TokenAccesso tokenAccesso = new TokenAccesso()
			{
				CodiceFiscaleEnte = ente.CodiceFiscaleEnte,
				CodiceFiscale = utente.FiscalNumber,
				Albo = ente.Albo,
				Username = ente.Username,
				Utilizzato = false,
				DataScadenza = DateTime.UtcNow.AddSeconds(Parametri.TokenAccessoDurataSecondi)
			};
			context.Add(tokenAccesso);
			context.SaveChanges();
			string token = tokenAccesso.Id.ToString();
			return Redirect($"{Parametri.UrlAccessoHelios}/?token={token}");
		}


		/// <summary>
		/// Metodo per la verifica del token di accesso al sistema unico
		/// </summary>
		/// <param name="token"></param>
		/// <returns></returns>
		[HttpGet]
		public IActionResult CheckToken(string token)
		{
			/*TokenAccessoInfo tokenInfo = VerifyAccessoToken(token);
			if (!tokenInfo.IsValid)
			{
				Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Token non valido",parameters:token);
				return Json(new { success = false,message = "Token non valido" });

			}
			if (tokenInfo.IsExpired)
			{
				Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Token scaduto", parameters: token);
				return Json(new { success = false, message = "Token non valido" });

			}*/
			Guid tokenId;
			if(!Guid.TryParse(token,out tokenId)){
				Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Token non valido", parameters: token);
				return Json(new { success = false, message = "Token non valido" });
			};

			using (TransactionScope scope = new TransactionScope())
			{
				TokenAccesso tokenAccesso = context.TokenAccesso.FirstOrDefault(t => t.Id == tokenId);
				if (tokenAccesso == null)
				{
					Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Token non trovato", parameters: token);
					return Json(new { success = false, message = "Token non valido" });
				}
				//if (tokenAccesso.CodiceFiscale != tokenInfo.Token.CodiceFiscale)
				//{
				//	Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "CF Utente alterato", parameters: token);
				//	return Json(new { success = false, message = "Token non valido" });
				//}
				//if (tokenAccesso.CodiceFiscaleEnte != tokenInfo.Token.CodiceFiscaleEnte)
				//{
				//	Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "CF Ente alterato", parameters: token);
				//	return Json(new { success = false, message = "Token non valido" });
				//}
				//if (tokenAccesso.Albo != tokenInfo.Token.Albo)
				//{
				//	Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Albo alterato", parameters: token);
				//	return Json(new { success = false, message = "Token non valido" });
				//}
				if (tokenAccesso.Utilizzato)
				{
					Log.Error(LogEvent.ERRORE_ACCESSO_HELIOS, "Token già utilizzato", parameters: token);
					return Json(new { success = false, message = "Token non valido" });

				}
				tokenAccesso.Utilizzato = true;
				context.SaveChanges();
				scope.Complete();
				return Json(new {	success = true,
									CodiceFiscaleEnte = tokenAccesso.CodiceFiscaleEnte,
									CodiceFiscale = tokenAccesso.CodiceFiscale,
									Username = tokenAccesso.Username,
									albo = tokenAccesso.Albo
				});
			}

		}


		public IActionResult Logoff()
		{
			Log.Information(LogEvent.DISCONNESSIONE);
			Response.Cookies.Delete("jwtToken");
			HttpContext.Session.Remove("Registrazione");
			return RedirectToAction("Index","Home");
		}



	}

}

SistemaUnico/Registrazione/Views/Accesso/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
	string message = TempData["message"]?.ToString();
	string warning = TempData["warning"]?.ToString();
	bool rigaPari = false;
}
@model List<UtenteEnte>

@if (!string.IsNullOrEmpty(message))
{
	<div class="alert alert-success" role="success">
		@message
	</div>
}
@if (!string.IsNullOrEmpty(warning))
{
	<div class="alert alert-warning" role="warning">
		@warning
	</div>
}

@* Enti Titolari*@
<div class="container border rounded p-3">
	<h4>Enti titolari di Servizio Civile Universale</h4>

	@* Se sono presenti Enti registrati*@
	@if (Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCU").Any())
	{
		<h5>Accesso Sistema Unico</h5>
		<div class="container grid">
			@using (Html.BeginForm("Accedi", "Accesso", FormMethod.Post))
			{
				<input type="hidden" name="Albo" value="SCU" />

				@foreach (UtenteEnte item in Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCU"))
				{
					string tipoUtente = "";
					if (item.RappresentanteLegale == true)
					{
						tipoUtente = "come Rappresentante Legale";
					}
					else if (item.UtenzaSede ==0)
					{
						tipoUtente = "come Delegato";
					}
					else if (item.UtenzaSede == 2)
					{
						tipoUtente = "come Utente";
					}
					string denominazione = $"Ente \"{item.Denominazione}\"";
					if (item.UtenzaSede == 1)
					{
						denominazione = item.Denominazione;
					}
					<div class="row @(rigaPari?"alternate":"")">
						<div class="col-sm">@denominazione</div>
						<div class="col-sm"> <button type="submit" name="Username" value="@item.Username" class="btn btn-primary col-md-12">Accesso @tipoUtente</button> </div>
					</div>
					rigaPari = !rigaPari;
				}
			}
		</div>
		<br />
	}

	<h5>Registrazione</h5>
	<div class="container grid">
		@if (Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCU").Any())
		{

			@using (Html.BeginForm("RegistraEnte", "Registrazione", FormMethod.Post))
			{
				<input type="hidden" name="albo" value="SCU" />
				@foreach (UtenteEnte item in Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCU"))
				{
					<div class="row @(rigaPari?"alternate":"")">
						<div class="col-sm">Ente "@item.Denominazione"</div>
						<div class="col-sm">
							@*<button type="submit" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte" class="btn btn-primary">Accedi come @tipoUtente</button>*@
							<button type="submit" class="btn btn-primary col-md-12" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte">Registrazione del Rappresentante Legale</button>
						</div>
					</div>
					rigaPari = !rigaPari;
				}
			}
		}


		@using (Html.BeginForm("SelezionaTipologia", "Registrazione", FormMethod.Post))
		{
			<input type="hidden" name="fromAccesso" value="true" />
			<input type="hidden" name="Albo" value="SCU" />

			<div class="row @(rigaPari?"alternate":"")">
				<div class="col-sm">Nuovo Ente Titolare</div>
				<div class="col-sm">
					<button type="submit" class="btn btn-primary col-md-12" name="EnteTitolare" value="true">Registrazione del Rappresentante Legale</button>
				</div>
			</div>
			rigaPari = !rigaPari;
		}
	</div>
</div>
<br />
@* Enti di Accoglienza*@
@if (Model.Where(x => x.CodiceFiscaleEntePadre != null).Any())
{

	<div class="container border rounded p-3">
		<h4>Enti di Accoglienza</h4>

		@* Se sono presenti Enti registrati*@
		@if (Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre != null).Any())
		{
			<h5>Accesso Sistema Unico</h5>
			<div class="container grid">
				@using (Html.BeginForm("Accedi", "Accesso", FormMethod.Post))
				{

					<input type="hidden" name="Albo" value="SCU" />
					@foreach (UtenteEnte item in Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre != null))
					{
						string tipoUtente = "Delegato";
						if (item.RappresentanteLegale == true)
						{
							tipoUtente = "Rappresentante Legale";
						}
						else if (item.UtenzaSede == 2)
						{
							tipoUtente = "Utente";
						}
						<div class="row @(rigaPari?"alternate":"")">
							<div class="col-sm">Ente "@item.Denominazione"</div>
							<div class="col-sm"> <button type="submit" name="Username" value="@item.Username" class="btn btn-primary col-md-12">Accesso come @tipoUtente</button> </div>
						</div>
						rigaPari = !rigaPari;
					}
				}
			</div>
			<br />
		}

		@if (Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre != null).Any())
		{

			<h5>Registrazione</h5>
			<div class="container grid">
				@using (Html.BeginForm("RegistraEnte", "Registrazione", FormMethod.Post))
				{
					<input type="hidden" name="Albo" value="SCU" />
					<input type="hidden" name="fromAccesso" value="true" />
					@foreach (UtenteEnte item in Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre != null && x.IdCategoriaEnte != null))
					{
						<div class="row @(rigaPari ? "alternate" : "")">
							<div class="col-sm">Ente "@item.Denominazione"</div>
							<div class="col-sm">
								@*<button type="submit" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte" class="btn btn-primary">Accedi come @tipoUtente</button>*@
								<button type="submit" class="btn btn-primary col-md-12" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte">Registrazione del Rappresentante Legale</button>
							</div>
						</div>
						rigaPari = !rigaPari;
					}
				}
				@using (Html.BeginForm("SelezionaTipologia", "Registrazione", FormMethod.Post))
				{
					<input type="hidden" name="EnteTitolare" value="false" />
					<input type="hidden" name="fromAccesso" value="true" />
					@foreach (UtenteEnte item in Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre != null && x.IdCategoriaEnte == null))
					{

						<div class="row @(rigaPari ? "alternate" : "")">
							<div class="col-sm">@item.Denominazione</div>
							<div class="col-sm">
								<button type="submit" class="btn btn-primary col-md-12" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte">Registrazione del Rappresentante Legale</button>
							</div>
						</div>
						rigaPari = !rigaPari;
					}
				}
			</div>

		}

		@*@using (Html.BeginForm("SelezionaTipologia", "Registrazione", FormMethod.Post))
			{
				<input type="hidden" name="fromAccesso" value="true" />
				<div class="row @(rigaPari?"alternate":"")">
					<div class="col-sm">Ente di Accoglienza</div>
					<div class="col-sm">
						<button type="submit" class="btn btn-primary col-md-12" name="EnteTitolare" value="false">Registrazione del Rappresentante Legale</button>
					</div>
				</div>

			}*@
	</div>
}

@* Enti SCN
<div class="container border rounded p-3">
	<h4>Enti Titolari di Servizio Civile Nazionale</h4>

	@if (Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCN").Any())
	{
		<h5>Accesso Sistema Unico</h5>
		<div class="container grid">
			@using (Html.BeginForm("Accedi", "Accesso", FormMethod.Post))
			{
				<input type="hidden" name="Albo" value="SCN" />

				@foreach (UtenteEnte item in Model.Where(x => x.Username != null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCN"))
				{
					string tipoUtente = "Delegato";
					if (item.RappresentanteLegale == true)
					{
						tipoUtente = "Rappresentante Legale";
					}
					string denominazione = $"Ente \"{item.Denominazione}\"";
					if (item.UtenzaSede == 1)
					{
						denominazione = item.Denominazione;
					}
					<div class="row @(rigaPari?"alternate":"")">
						<div class="col-sm">@denominazione</div>
						<div class="col-sm"> <button type="submit" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte" class="btn btn-primary col-md-12">Accesso come @tipoUtente</button> </div>
					</div>
					rigaPari = !rigaPari;
				}
			}
		</div>
		<br />

	}
	<h5>Registrazione</h5>
	<div class="container grid">
		@using (Html.BeginForm("RegistraEnte", "Registrazione", FormMethod.Post))
		{
			<input type="hidden" name="albo" value="SCN" />
			@foreach (UtenteEnte item in Model.Where(x => x.Username == null && x.CodiceFiscaleEntePadre == null && x.Albo == "SCN"))
			{
				<div class="row @(rigaPari?"alternate":"")">
					<div class="col-sm">Ente "@item.Denominazione" (Albo SCN)</div>
					<div class="col-sm">

						<button type="submit" class="btn btn-primary col-md-12" name="CodiceFiscaleEnte" value="@item.CodiceFiscaleEnte">Registrazione del Rappresentante Legale</button>
					</div>
				</div>
				rigaPari = !rigaPari;
			}
		}
		@using (Html.BeginForm("VariazioneRappresentante", "Registrazione", FormMethod.Post))
		{
			<input type="hidden" name="fromAccesso" value="true" />

			<div class="row @(rigaPari?"alternate":"")">
				<div class="col-sm">Ente Titolare Esistente</div>
				<div class="col-sm">
					<button type="submit" class="btn btn-primary col-md-12" name="EnteTitolare" value="true">Variazione del Rappresentante Legale</button>
				</div>
			</div>
			rigaPari = !rigaPari;
		}

	</div>

</div>

*@

SistemaUnico/Registrazione/Views/Accesso/Spid.cshtml
@using static RegistrazioneSistemaUnico.Helpers.Helper;
@{
	ViewData["Title"] = "Accesso SSPID";
}
@model Accesso
<div class="text-center">
	<h1 class="display-4">Accesso con SPID</h1>
	<p>Simulazione accesso tramite SPID</p>
	@using (Html.BeginForm("LoginSpid", "Accesso", FormMethod.Post))
	{
	<div class="row">
		@Html.InputFor(x => x.CodiceFiscale, cssClass: "col-md-6")
		@Html.InputFor(x => x.DataNascita, cssClass: "col-md-6")
	</div>
	<div class="row">
		@Html.InputFor(x => x.Nome, cssClass: "col-md-6")
		@Html.InputFor(x => x.Cognome, cssClass: "col-md-6")
	</div>
	<input class="btn btn-primary col-md-3 col-sm-6" type="submit" value="Accesso">
	}
</div>